In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)

In [2]:
months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

categories = [
    "Electronics",
    "Furniture",
    "Grocery",
    "Clothing",
    "Sports"
]

rows = 300

df = pd.DataFrame({
    "Invoice": np.arange(1001,1001+rows),
    "Month": np.random.choice(months,rows),
    "Category": np.random.choice(categories,rows),
    "Revenue": np.random.randint(5000,80000,rows),
    "Quantity": np.random.randint(1,40,rows),
    "Discount": np.random.randint(0,31,rows),
    "Profit": np.random.randint(1000,20000,rows)
})

df.head()

   Invoice Month     Category  Revenue  Quantity  Discount  Profit
0     1001   Jul      Grocery    77592         4        10    9202
1     1002   Apr      Grocery    49261        19        13    2868
2     1003   Nov     Clothing     6542        20         3   15561
3     1004   Aug  Electronics    26677        33        25   16512
4     1005   May     Clothing    51732        20        25   15899

In [3]:
df.to_csv("retail_sales.csv",index=False)
print ("Dataset stored Successfully")

Dataset stored Successfully

In [4]:
sales = pd.read_csv("retail_sales.csv")
sales.head()

   Invoice Month     Category  Revenue  Quantity  Discount  Profit
0     1001   Jul      Grocery    77592         4        10    9202
1     1002   Apr      Grocery    49261        19        13    2868
2     1003   Nov     Clothing     6542        20         3   15561
3     1004   Aug  Electronics    26677        33        25   16512
4     1005   May     Clothing    51732        20        25   15899

In [5]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Invoice   300 non-null    int64
 1   Month     300 non-null    str
 2   Category  300 non-null    str
 3   Revenue   300 non-null    int64
 4   Quantity  300 non-null    int64
 5   Discount  300 non-null    int64
 6   Profit    300 non-null    int64
dtypes: int64(5), str(2)
memory usage: 19.8 KB

In [6]:
sales.isnull().sum()

Invoice     0
Month       0
Category    0
Revenue     0
Quantity    0
Discount    0
Profit      0
dtype: int64

In [7]:
print("Total Records :", len(sales))
print("Total Columns :", len(sales.columns))

print("\nColumns")
print(sales.columns)

print("\nData Types")
print(sales.dtypes)

Total Records : 300
Total Columns : 7

Columns
Index(['Invoice', 'Month', 'Category', 'Revenue', 'Quantity', 'Discount',
       'Profit'],
      dtype='str')

Data Types
Invoice     int64
Month         str
Category      str
Revenue     int64
Quantity    int64
Discount    int64
Profit      int64
dtype: object

In [8]:
sales.describe()

           Invoice       Revenue    Quantity    Discount        Profit
count   300.000000    300.000000  300.000000  300.000000    300.000000
mean   1150.500000  39718.556667   20.050000   15.200000  10909.816667
std      86.746758  21243.225629   11.539702    8.796472   5718.845518
min    1001.000000   5055.000000    1.000000    0.000000   1089.000000
25%    1075.750000  22133.000000   10.000000    8.000000   5961.750000
50%    1150.500000  39553.500000   21.000000   15.500000  11141.500000
75%    1225.250000  58350.750000   30.000000   23.000000  16072.500000
max    1300.000000  78963.000000   39.000000   30.000000  19988.000000